export const RAW_CSV_DATA = `Section,Title,Content,Artifact,Link,Tags,Date,Item Type,Status,Order,Subsection
Flagship Projects,Program Quality Framework (RBM/FIAP) for ESA – Ethiopia Anchor,"Designed and operationalized a Program Quality Framework with QAG gates (design→inception→implementation→close-out), standard logframes, MEL plans, and evaluation ToRs—reducing rework and lifting donor-compliance readiness across partner portfolios.",/mnt/data/Annual Country report -Ethiopia (July 2024 - April 2025) 1.pdf,,"Program Quality,GAC,FIAP,RBM,MEAL,Governance",2025-05-01,Project,Featured,1,Program Excellence
Flagship Projects,Indicator Tracking Matrix (ITM) + Quarterly Performance Assessments,"Built Ethiopia’s ITM with baselines, targets, formulas, and verification; instituted quarterly performance dialogues and learning reviews to route evidence into work-plan reprioritization.",/mnt/data/VOICE-Ethiopia-Project-Performance-Analysis 2025-11-10.pdf,,"MEAL,ITM,Quarterly Reviews,Learning",2025-11-10,Project,Ready,2,MEAL Systems
Flagship Projects,Security Guide & PSEAH Country Info + Monthly Risk Watch,Updated Ethiopia Security Guide and PSEAH information; established monthly security/risk watch and evacuation communications—embedding duty-of-care within portfolio rhythms.,/mnt/data/Annual Country report -Ethiopia (July 2024 - April 2025) 1.pdf,,"Safeguarding,PSEAH,Security,Risk",2025-04-30,Project,Ready,3,Risk & Safeguarding
Flagship Projects,Gender Audits → Corrective Actions & 7‑Year Capacity Plans,"Coordinated organizational diagnostics and gender audits; translated findings into corrective actions and multi‑year capacity-building plans for VCP partners (ECYDO, NEWA, Progynist, ACSO).",/mnt/data/2025 Q1 VCP REPORT_EN.pdf,,"GESI,Gender Audit,Capacity Building,VCP",2025-06-30,Project,Ready,4,GESI/WEE
Flagship Projects,Women‑Led Peacebuilding Networks – Concept (FIAP‑aligned),"Co‑developed a regional concept note aligning to FIAP; defined ToC, results chains, and MEL architecture; prepared reusable annex/evidence packs for capture-to-submission reuse.",/mnt/data/GAC Concept Note Ethiopia (3).pdf,,"GAC,FIAP,Peacebuilding,Proposal,ToC",2025-09-15,Project,Ready,5,Proposal Design
Flagship Projects,Coffee WEE Concept – Results Chain & MEL Annex Kit,Designed results chain and MEL annex kit for Coffee WEE concept; standardized templates improved first‑time‑right technical quality and compliance.,/mnt/data/Project Concepts for Cooperative Development in Abaya.docx,,"WEE,Results Chain,MEL Annex,Templates",2025-08-25,Project,Ready,6,Proposal Design
Advisory & Governance,Proposal Pipeline Governance (Capture→Bid/No‑Bid→Red‑Team),"Instituted regional pipeline governance with capture plans, donor intel briefs, bid/no-bid criteria, red‑team reviews, and reusable MEL annex kits—shortening cycles and raising compliance.",/mnt/data/2025 Q1 VCP REPORT_EN.pdf,,"Pipeline,Governance,Red‑Team,Annex Kits",2025-06-30,Case Study,Ready,7,Resource Mobilization
Advisory & Governance,Community of Practice & Artifacts Library,Launched monthly clinics and a shared artifacts repository to diffuse standards and tools across partners; reduced rework and accelerated onboarding.,/mnt/data/Annual Country report -Ethiopia (July 2024 - April 2025) 1.pdf,,"CoP,Standards,Tooling,Onboarding",2025-04-15,Case Study,Ready,8,Knowledge & Learning
Research & Learning,Internal Mid‑Term Evaluation – Learning‑Oriented Design,"Drafted a learning‑oriented internal MTE with adaptive management focus; defined sentinel indicators, assumption tracking, and decision‑gate routines.",/mnt/data/MTE Proposal 2025-11-06.pdf,,"Evaluation,MTE,Adaptive Learning,Sentinel Indicators",2025-11-06,Evaluation,Ready,9,Evaluation Design
Research & Learning,Formative Evaluation Briefing – ESA Volunteer Cooperation Context,Synthesized formative evaluation insights; captured cross‑country lessons on gender‑transformative programming and capacity‑building pathways.,/mnt/data/FORMATIVE-EVALUATION-BRIEFING-NOTE.pdf,,"Formative Evaluation,Learning Brief,ESA",2025-09-30,Brief,Ready,10,Learning Briefs
Training & ToT,ALLMEL Refresher & Outcome Measurement Clinics,"Delivered ToT and coaching on RBM, outcome measurement, adaptive routines; embedded quality gates into performance rhythms and decision logs.",/mnt/data/2025 Q1 VCP REPORT_EN.pdf,,"ToT,RBM,Outcome Measurement,Adaptive",2025-06-25,Training,Ready,11,Capacity Building
Quality Improvement (Health),Hospital QI Governance – Run Charts & A3 Problem Solving,"Applied QI governance to clinical operations (driver/fishbone diagrams, run charts, PDSA cycles); codified change routines transferable to program ops.",,,"Hospital QI,Run Charts,PDSA,Governance",2025-12-01,Case Study,Ready,12,QI Systems
Methods & Frameworks,Theory of Change (ToC) – Locally‑Led Participatory Project Cycle,"Documented a ToC emphasizing locally‑led, participatory cycles with embedded learning loops; aligned to FIAP and donor MEL requirements.",/mnt/data/Dirshayes-Theory-of-Change-ToC.pdf,,"ToC,LLPPC,FIAP,Learning Loops",2025-07-31,Framework,Ready,13,Program Design
Credentials,POTI – Peace Operations Specialized Training Certificate (Civilian Service),"Completed an eight‑course specialization including Protection of Civilians, IHL/LOAC, Humanitarian Relief, Human Rights and leadership in peace ops.",/mnt/data/Dirshaye All education and Certficates Merged.pdf,,"POTI,Peace Ops,Certification",2022-06-13,Certification,Ready,14,Professional Training
Credentials,"Master’s in International Cooperation & Humanitarian Aid (1,500h)","Graduate professional program spanning humanitarian response, project management (LFA/RBM), ethics, protection, and disaster risk reduction.",/mnt/data/Dirshaye All education and Certficates Merged.pdf,,"Master’s,RBM,Humanitarian",2021-11-10,Degree,Ready,15,Academic
Flagship Projects,Annual VCP Country Report – Ethiopia,"Produced donor‑ready reporting with outcomes synthesis, risks and mitigations, partner diagnostics and mandate planning (2024–2025).",/mnt/data/Annual Country report -Ethiopia (July 2024 - April 2025) 1.pdf,,"Reporting,GAC,VCP,Country Report",2025-04-30,Report,Ready,17,Donor Reporting
Flagship Projects,Quarterly Report – Y6 Q1 (ESA highlights),"Captured gender‑audit rollouts, donor‑mapping workshops, and concept ideation; documented program‑excellence gains across partners.",/mnt/data/2025 Q1 VCP REPORT_EN.pdf,,"Quarterly,ESA,Gender Audit,Donor Mapping",2025-06-30,Report,Ready,18,Program Excellence`;